### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by Physikbuddha** [netresearch/t3x-rte_ckeditor_image#152] opened 2022-01-26 12:39 UTC
The extension should either state its PHP requirements in the composer.json (^7.4) or be compatible with PHP ^8.0
Right now, several PHP warnings are issued when saving the RTE with images.

**Comment by TechnicalAthere** [comment] 2023-01-25 13:17
I am closing the issue because the error is now no longer reproducible.

**Setup** 
 - TYPO3 v. 11.5.22
 - PHP v. 8.0.27

**Closed by TechnicalAthere** 2023-01-25 13:17 UTC
Labels: php
