### ISSUE TITLE
Version 8.7.6 breaks "Umlauts" in links

### ISSUE THREAD

**Issue by bigahuna** [netresearch/t3x-rte_ckeditor_image#35] opened 2018-11-30 10:06 UTC
We have pi_flexform fields with links that contain umlauts (äöü) in the link label. After updating the rte_ckeditor_image plugin from 8.7.5 to 8.7.6 the utf8-encoding of all this umlauts is displayed wrong (i.e. "fÃ¼r "instead of "für"). Only links are affected.

The text inside the database is encoded correctly ("für").

Tested with  TYPO3 8.7.20 and  TYPO3 8.7.19 with php 7.1.24 on CentOs

**Comment by muh-nr** [comment] 2018-11-30 12:01
@bigahuna 
Thanks for your hint, fixed in current master.

**Comment by prdt3e** [comment] 2018-11-30 14:16
@muh-nr 
what's the function "tags.a.preUserFunc = Netresearch \ RteCKEditorImage \ Controller \ ImageLinkRenderingController-> renderImages" all about?

is this not unnecessary?
Is not that very dangerous to touch "all links"?

**Comment by muh-nr** [comment] 2018-11-30 14:37
@prdt3e 
Do you know another way to render the linked images?

**Comment by prdt3e** [comment] 2018-11-30 14:43
What exactly do you mean? 
For me, the linked images always worked?
You mean this ?:
```php
<p><a href="t3://page?uid=11"><img alt="" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="1" data-htmlarea-zoom="true" height="150" src="http://site.de/fileadmin/_processed_/f/c/csm_Lighthouse_4c52027134.jpg" title="gffghh asdsdds" width="200" /></a></p>
```

**Comment by muh-nr** [comment] 2018-12-02 08:47
@prdt3e 
Thanks for your helpful input!

The link renderer processes images that are linked with the default link wizard in CKE.
Without renderer you won't be able to process the images and get an output like this by default (fluid_styled_content):

```
<a href="http://www.test.com" target="_blank">
    <img alt="" height="231"
         src="fileadmin/_processed_/9/2/csm_img01_6a15a47a6c.jpg"
         title="custom-title" 
         width="320" 
         style=""/>
</a>
```

It's not possible to:
* add fallback for title/alt
* remove empty style attr.
* manipulate image html (e.g. add a figure tag)
* add classes for e.g. alignment later on

How did you prevent this behavior?

**Comment by prdt3e** [comment] 2018-12-02 12:07
Okay i understand.
The problem is https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php 4043 / 4133  is no recursive if the element is no externalblock.

Now, the idea would be to set the img as an external block. but I do not see parsefunc for externalblock.
Yesterday I already considered several approaches.
Very difficult. I think again.

**Comment by prdt3e** [comment] 2018-12-02 12:12
My other approach was to hang parsefunc on tt_content to do that earlier.
tt_content,parsefunc -> img
lib.parsefunc -> a

**Comment by prdt3e** [comment] 2018-12-02 12:50
the problem I see is:
fluid_styled_content (https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid_styled_content/Configuration/TypoScript/Helper/ParseFunc.typoscript) (24) itself has settings for the a-tag-parser and with userfunc is it all gone?

in principle we would only have to do the following:
lib.parseFunc.tags.a.if.is.isFalse = this atag (child of them) has an image with attribute data-htmlarea-file-uid
(ContentObjectRenderer.php / 4150) 
When this happens, the return is the element. And the parser should continue to run to the child.

**Comment by prdt3e** [comment] 2018-12-02 14:18
you can delete 2nd parser:
```php
tt_content.stdWrap.parseFunc{
    tags.img = TEXT
    tags.img {
        current = 1
        preUserFunc = Netresearch\RteCKEditorImage\Controller\ImageRenderingController->renderImageAttributes
    }
    nonTypoTagStdWrap.HTMLparser.tags.img.fixAttrib {
        allparams.unset = 1
        data-htmlarea-file-uid.unset = 1
        data-htmlarea-file-table.unset = 1
        data-htmlarea-zoom.unset = 1
    }
}
```
But you have to check it again.
There are often $fileUid with 0.

**Comment by prdt3e** [comment] 2018-12-02 16:15
@muh-nr 
i have solution. 
We do it as described above:
tt_content.parsefunc -> img
lib.parsefunc -> a
The rendering for "all" images.

```php
tt_content.stdWrap.parseFunc{
    tags.img = TEXT
    tags.img {
        current = 1
        preUserFunc = Netresearch\RteCKEditorImage\Controller\ImageRenderingController->renderImageAttributes
    }
}
```
But there are 2 problems that arise from it:
1. You need to rewrite the code of ImageRenderingController.php.
1.1 if ($fileUid) needs to be adjusted, as 0 is often passed from images that have no data-htmlarea-file-uid.
1.2 the if must be increased so that only a return takes place if data-htmlarea-file-uid is set
1.3 the parameters allparams, data-htmlarea-file-uid, data-htmlarea-file-table, data-htmlarea-zoom have to be deleted in PHP.
2. If zoom and link is active we get <a> <a> </a> </a> (but I still find a solution for that)

I think that will be the solution. That's the cleanest way.

**Comment by muh-nr** [comment] 2018-12-02 16:37
Thank you so much for investigating a solution for all images.
I'm hopefully going to have try next week.

**Comment by prdt3e** [comment] 2018-12-02 16:56
I'm just about to make a condition for the parser.
Like this:
```php
tt_content.stdWrap.parseFunc{
    tags.img = TEXT
    tags.img {
        current = 1
        preUserFunc = Netresearch\RteCKEditorImage\Controller\ImageRenderingController->renderImageAttributes
    }
    if.isTrue.cObject.preUserFunc = Netresearch\RteCKEditorImage\Controller\ImageRenderingController->ifTScondition
}
```

So we get it out that even "our" pictures come through the parser.

**Comment by muh-nr** [comment] 2018-12-02 20:31
@prdt3e

Sounds good,
we could also detect it if $imageAttributes['allParams']) exists.
Do you know how to get the image uid.
Currently with your approach there is only the source: $imageAttributes['allParams']).

I could extract the image uid with the DOM method from ImageLinkRenderingController.php, but there is probably a better way I couldn't find so fare.

Greetings
Mathias

**Comment by muh-nr** [comment] 2018-12-02 22:55
I have had a try with changing to tt_content.stdWrap.parseFunc.

I used the DOM rendering method rom imageLinkRenderer just to get the image uid, 
but without parsing any content.

See branch [dev#35-linked-image-renderer](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev%2335-linked-image-renderer)

@prdt3e 
Maybe you'l find a better way, but it't a start.

**Comment by prdt3e** [comment] 2018-12-03 14:51
Many Thanks!
Very nice!

Just delete the following:
```php
lib.parseFunc {
    nonTypoTagStdWrap.HTMLparser.tags.img.fixAttrib {
        allparams.unset = 1
        data-htmlarea-file-uid.unset = 1
        data-htmlarea-file-table.unset = 1
        data-htmlarea-zoom.unset = 1
    }
}
}
```
then you have parameters that you need in your Script.

Then you delete allparams, data-htmlarea-file-uid, data-htmlarea-file-table, data-htmlarea-zoom via PHP.

Now we just have one more solution for:
```php 
<a> <a> </a> </a> 
```
This happens when you have an external link and accidentally have zoom enabled.
I think for this we have to make a solution in JavaScript when inserting.

Thanks!

**Comment by muh-nr** [comment] 2018-12-03 21:16
@prdt3e 
Shame on me... I thought I would have tested this...

I cleaned up the renderer.
See branch [dev#35-linked-image-renderer](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev%2335-linked-image-renderer)

The <a> tag problem still needs to be solved.

**Comment by prdt3e** [comment] 2018-12-03 23:03
I think it will be the best if:
if ($ imageAttributes ['data-htmlarea-zoom'] && isset ($ file) && $ file) {
to expand with a new IF.

```php 
if ($ imageAttributes ['data-htmlarea-zoom'] && isset ($ file) && $ file) {
      if($this->muh-nrparser()){

      }
}
```
New IF? performance.
Sorry! 
We need your parser for bodytext again.
muh-nrparser check the current Image and check with domfunc to the parent if is not a atag.
Because the children condition, this parser is not executed often.

**Comment by prdt3e** [comment] 2018-12-04 10:48
We have to stop this approach.
I've tried it with an extension, that's nothing because the data is not in tt_content.

So lib.parseFunc is needed.
We could use both.
But not nice

**Comment by mbrodala** [comment] 2018-12-06 13:52
Version 8.7.7 and newer fixes the issue here.

**Comment by muh-nr** [comment] 2018-12-06 14:03
@magicsunday 
Glad to hear!

@prdt3e 
Let's continue here: #42

**Closed by muh-nr** 2018-12-06 14:03 UTC
