### ISSUE TITLE
Strange behaviour when writing only 1 word in first paragraph

### ISSUE THREAD

**Issue by timofo** [netresearch/t3x-rte_ckeditor_image#164] opened 2022-05-04 13:32 UTC
If you write something like

`xxx`
`yyy`

and you save it, you get the error:
`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320286857: File /<p>xxx</p> <p>yyy</p> is not valid (".." and "//" is not allowed in path). | TYPO3\CMS\Core\Resource\Exception\InvalidPathException thrown in file /html/typo3/public/typo3/sysext/core/Classes/Resource/Driver/AbstractHierarchicalFilesystemDriver.php in line 53.
`

If you write (more than 1 word in first paragraph)

`xxx xxx`
`yyy`

and save, there is no error.

If i remove "rte-ckeditor-image" from extension list, the error is not there. 
So i think it has something to do with the extension. And because the error says something with "FileSystemDriver".

**Comment by AnatoliiPak** [comment] 2022-05-23 12:53
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94741-RegisterSoftReferenceParsersViaDI.html

```
public function parse(string $table, string $field, int $uid, string $content, string $structurePath = '') : SoftReferenceParserResult
    {
        $this->setTokenIdBasePrefix($table, (string)$uid, $field, $structurePath);

        switch ($this->parserKey) {
            case 'rtehtmlarea_images':
                $retVal = $this->findRef_rtehtmlarea_images($content);
                break;
            default:
                $retVal = false;
        }
        return $retVal;
    }
```
```
public function findRef_rtehtmlarea_images($content)
    {
        $retVal = false;
        // Start HTML parser and split content by image tag
        $this->htmlParser = GeneralUtility::makeInstance(HtmlParser::class);
        $this->splittedContentTags = $this->htmlParser->splitTags('img', $content);

        $images = $this->findImagesWithDataUid();

        // Assemble result array
        if (!empty($images)) {
            $retVal = [
                'content' => implode('', $this->splittedContentTags),
                'elements' => $images
            ];
        }

        return SoftReferenceParserResult::create(
            implode(',', $this->splittedContentTags),
            $images
        );
    }
```

**Comment by marcelbaklouti** [comment] 2022-07-11 11:10
@CybotTM Is there a fix for this?

**Comment by CybotTM** [comment] 2022-07-13 10:38
@marcelbaklouti so far no incoming merge request which fixes this issue.

**Comment by cnmarco** [comment] 2022-08-12 05:03
I can confirm this bug exists with version 11.0.2 from https://extensions.typo3.org/extension/rte_ckeditor_image.
The error also occurs when you try to check the reference index via DB Check module.

However, in version 11.0.4 here from github it seems to be solved, I could not reproduce it anymore.

**Comment by vergissberlin** [comment] 2022-08-31 07:28
@cnmarco Thank you for testing.

**Comment by CybotTM** [comment] 2022-09-01 07:14
@vergissberlin  this issue is not done - as the problem still persists.
Solution is to update TER with the newest releases.

**Comment by CybotTM** [comment] 2022-09-01 08:57
Latest versions are also available in TER now

https://extensions.typo3.org/extension/rte_ckeditor_image

**Closed by CybotTM** 2022-09-01 08:57 UTC
Labels: bug, help wanted
