### ISSUE TITLE
special rte-content does not work with php >=8.0

### ISSUE THREAD

**Issue by subnoodle** [netresearch/t3x-rte_ckeditor_image#201] opened 2022-12-10 15:15 UTC
Hi, 
i hit an exception when using this extension with a "special button setup" like this with PHP 8.1 and 8.0; in PHP 7.4 it runs :

RTE-Content:
```
<p class="text-center"><a class="btn btn-background" href="t3://page?uid=476" role="button">Unsere Annahmestellen</a>&nbsp;<img alt="" data-alt-override="true" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="5819" data-title-override="true" src="/fileadmin/Website-2022/Abschnitt-Mitmach-Portal/Icons-Auswahl/Annahmestelle-5.svg" style="height:50px; width:50px" /></p>

<p class="text-center"><a class="btn btn-background" href="t3://page?uid=498" role="button">Unsere Förderprojekte</a>&nbsp;<img alt="" data-alt-override="true" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="5770" data-title-override="true" src="/fileadmin/Website-2022/Abschnitt-Mitmach-Portal/Icons-Auswahl/Foerderprojekt-opt.svg" style="height:50px; width:50px" /></p>
```

Exception:
```

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key 1 in /html/typo3/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php line 3736
in /html/typo3/public/typo3/sysext/core/Classes/Error/ErrorHandler.php line 137

        }

        $message = self::ERROR_LEVEL_LABELS[$errorLevel] . ': ' . $errorMessage . ' in ' . $errorFile . ' line ' . $errorLine;
        if ($errorLevel & $this->exceptionalErrors) {
            throw new Exception($message, 1476107295);
        }

        $message = $this->getFormattedLogMessage($message);

at TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'Undefined array key 1', '/html/typo3/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php', 3736)
in /html/typo3/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php line 3736

                            $contentAccum[$contentAccumP - 1] = preg_replace('/' . CR . '?' . LF . '[ ]*$/', '', $contentAccum[$contentAccumP - 1]);
                            $contentAccum[$contentAccumP] = preg_replace('/^[ ]*' . CR . '?' . LF . '/', '', $contentAccum[$contentAccumP]);
                            $contentAccum[$contentAccumP] = preg_replace('/' . CR . '?' . LF . '[ ]*$/', '', $contentAccum[$contentAccumP]);
                        }
                        $this->data[$this->currentValKey] = $contentAccum[$contentAccumP];
                        $newInput = $this->cObjGetSingle($theName, $theConf, '/parseFunc/.tags.' . $tag[0]);
                        // fetch the content object
                        $contentAccum[$contentAccumP] = $newInput;
                        $contentAccumP++;

at TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->_parseFunc('<p class="text-center"><a class="btn btn-background" href="t3://page?uid=476" role="button">Unsere Annahmestellen</a>&nbsp;<img alt="" data-alt-override="true" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="5819" data-title-override="true" src="/fileadmin/Website-2022/Abschnitt-Mitmach-Portal/Icons-Auswahl/Annahmestelle-5.svg" style="" title="" width="50" height="50" /></p> <p class="text-center"><a class="btn btn-background" href="t3://page?uid=498" role="button">Unsere Förderprojekte</a>&nbsp;<img alt="" data-alt-override="true" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="5770" data-title-override="true" src="/fileadmin/Website-2022/Abschnitt-Mitmach-Portal/Icons-Auswahl/Foerderprojekt-opt.svg" style="" title="" width="50" height="50" /></p>', array('tags.' => array('img' => 'TEXT', 'img.' => array('current' => '1', 'preUserFunc' => 'Netresearch\\RteCKEditorImage\\Controller\\ImageRenderingController->renderImageAttributes'), 'a' => 'TEXT', 'a.' => array('current' => '1', 'preUserFunc' => 'Netresearch\\RteCKEditorImage\\Controller\\ImageLinkRenderingController->renderImages', 'typolink.' => array('parameter.' => array('data' => 'parameters:href'), 'title.' => array('data' => 'parameters:title'), 'ATagParams.' => array('data' => 'parameters:allParams'), 'target.' => array('data' => 'parameters:target'), 'extTarget' => '_blank', 'extTarget.' => array('override.' => array('data' => 'parameters:target')))), 'link' => 'TEXT', 'link.' => array('current' => '1', 'typolink.' => array('parameter.' => array('data' => 'parameters : allParams'), 'extTarget' => '_blank'), 'parseFunc.' => array('constants' => '1'))), 'nonTypoTagStdWrap.' => array('HTMLparser.' => array('tags.' => array('img.' => array('fixAttrib.' => array('allparams.' => array('unset' => '1'), 'data-htmlarea-file-uid.' => array('unset' => '1'), 'data-htmlarea-file-table.' => array('unset' => '1'), 'data-htmlarea-zoom.' => array('unset' => '1'), 'data-htmlarea-clickenlarge.' => array('unset' => '1'), 'data-title-override.' => array('unset' => '1'), 'data-alt-override.' => array('unset' => '1')))), 'keepNonMatchedTags' => '1', 'htmlSpecialChars' => '2'), 'HTMLparser' => '1', 'encapsLines.' => array('encapsTagList' => 'p, pre, h1, h2, h3, h4, h5, h6, hr, dt', 'remapTag.' => array('DIV' => 'P'), 'nonWrappedTag' => 'P', 'innerStdWrap_all.' => array('ifBlank' => '&nbsp;'))), 'makelinks' => '1', 'makelinks.' => array('http.' => array('keep' => 'path', 'extTarget' => '_blank'), 'mailto.' => array('keep' => 'path')), 'allowTags' => 'a, abbr, acronym, address, article, aside, b, bdo,big, blockquote, br, caption, center, cite, code, col,colgroup, dd, del, dfn, dl, div, dt, em, font,footer, header, h1, h2, h3, h4, h5, h6, hr, i, img,ins, kbd, label, li, link, meta, nav, ol, p, pre, q,samp, sdfield, section, small, span, strike, strong,style, sub, sup, table, thead, tbody, tfoot, td, th,tr, title, tt, u, ul, var,a, abbr, acronym, address, article, aside, b, bdo,big, blockquote, br, caption, center, cite, code, col,colgroup, dd, del, dfn, dl, div, dt, em, font,footer, header, h1, h2, h3, h4, h5, h6, hr, i, img,ins, kbd, label, li, link, meta, nav, ol, p, pre, q,samp, sdfield, section, small, span, strike, strong,style, sub, sup, table, thead, tbody, tfoot, td, th,tr, title, tt, u, ul, var', 'denyTags' => '*', 'sword' => '<span class="text-highlight">|</span>', 'constants' => '1', 'externalBlocks' => 'article, address, aside, blockquote, div, dd, dl, footer,header, nav, ol, section, table, ul, pre, figure', 'externalBlocks.' => array('ol.' => array('stripNL' => '1', 'stdWrap.' => array('parseFunc' => '< lib.parseFunc')), 'ul.' => array('stripNL' => '1', 'stdWrap.' => array('parseFunc' => '< lib.parseFunc', 'HTMLparser' => '1', 'HTMLparser.' => array('tags.' => array('ul.' => array('fixAttrib.' => array('class.' => array('default' => 'list-normal')))), 'keepNonMatchedTags' => '1'))), 'table.' => array('stripNL' => '1', 'stdWrap.' => array('wrap' => '<div class="table-responsive">|</div>'), 'HTMLtableCells' => '1', 'HTMLtableCells.' => array('default.' => array('stdWrap.' => array('parseFunc' => '< lib.parseFunc_RTE', 'parseFunc.' => array('nonTypoTagStdWrap.' => array('encapsLines.' => array('nonWrappedTag' => ''))))))), 'pre.' => array('stripNL' => '1', 'stdWrap.' => array('parseFunc.' => array('tags.' => array('img' => 'TEXT', 'img.' => array('current' => '1', 'preUserFunc' => 'Netresearch\\RteCKEditorImage\\Controller\\ImageRenderingController->renderImageAttributes'), 'a' => 'TEXT', 'a.' => array('current' => '1', 'preUserFunc' => 'Netresearch\\RteCKEditorImage\\Controller\\ImageLinkRenderingController->renderImages', 'typolink.' => array('parameter.' => array('data' => 'parameters:href'), 'title.' => array('data' => 'parameters:title'), 'ATagParams.' => array('data' => 'parameters:allParams'), 'target.' => array('data' => 'parameters:target'), 'extTarget' => '_blank', 'extTarget.' => array('override.' => array('data' => 'parameters:target')))), 'link' => 'TEXT', 'link.' => array('current' => '1', 'typolink.' => array('parameter.' => array('data' => 'parameters : allParams'), 'extTarget' => '_blank'), 'parseFunc.' => array('constants' => '1'))), 'nonTypoTagStdWrap.' => array('HTMLparser.' => array('tags.' => array('img.' => array('fixAttrib.' => array('allparams.' => array('unset' => '1'), 'data-htmlarea-file-uid.' => array('unset' => '1'), 'data-htmlarea-file-table.' => array('unset' => '1'), 'data-htmlarea-zoom.' => array('unset' => '1'), 'data-htmlarea-clickenlarge.' => array('unset' => '1'), 'data-title-override.' => array('unset' => '1'), 'data-alt-override.' => array('unset' => '1')))), 'keepNonMatchedTags' => '1', 'htmlSpecialChars' => '2'), 'HTMLparser' => '1'), 'makelinks' => '1', 'makelinks.' => array('http.' => array('keep' => 'path', 'extTarget' => '_blank'), 'mailto.' => array('keep' => 'path')), 'allowTags' => 'a, abbr, acronym, address, article, aside, b, bdo,big, blockquote, br, caption, center, cite, code, col,colgroup, dd, del, dfn, dl, div, dt, em, font,footer, header, h1, h2, h3, h4, h5, h6, hr, i, img,ins, kbd, label, li, link, meta, nav, ol, p, pre, q,samp, sdfield, section, small, span, strike, strong,style, sub, sup, table, thead, tbody, tfoot, td, th,tr, title, tt, u, ul, var,a, abbr, acronym, address, article, aside, b, bdo,big, blockquote, br, caption, center, cite, code, col,colgroup, dd, del, dfn, dl, div, dt, em, font,footer, header, h1, h2, h3, h4, h5, h6, hr, i, img,ins, kbd, label, li, link, meta, nav, ol, p, pre, q,samp, sdfield, section, small, span, strike, strong,style, sub, sup, table, thead, tbody, tfoot, td, th,tr, title, tt, u, ul, var', 'denyTags' => '*', 'sword' => '<span class="text-highlight">|</span>', 'constants' => '1'))), 'div.' => array('stripNL' => '1', 'callRecursive' => '1'), 'article.' => array('stripNL' => '1', 'callRecursive' => '1'), 'aside.' => array('stripNL' => '1', 'callRecursive' => '1'), 'figure.' => array('stripNL' => '1', 'callRecursive' => '1'), 'blockquote.' => array('stripNL' => '1', 'callRecursive' => '1'), 'footer.' => array('stripNL' => '1', 'callRecursive' => '1'), 'header.' => array('stripNL' => '1', 'callRecursive' => '1'), 'nav.' => array('stripNL' => '1', 'callRecursive' => '1'), 'section.' => array('stripNL' => '1', 'callRecursive' => '1'), 'dl.' => array('stripNL' => '1', 'callRecursive' => '1'), 'dd.' => array('stripNL' => '1', 'callRecursive' => '1')), 'htmlSanitize' => true))
```

When i uninstall the extension with php8, then the exception do not occure anymore.

Any clue?

Thx,, Thomas

**Comment by CybotTM** [comment] 2022-12-12 10:07
Hi,

@subnoodle, as a quick fix you could try disabling throwing PHP warnings as exceptions in TYPO3.

Can you please add the version of TYPO3 and rte_ckeditor_image you are using?

**Comment by subnoodle** [comment] 2022-12-12 14:13
Hi @CybotTM ,
the version is v11.0.6.
Also, i entered the issue again: when i turned off the elements containing images, it worked again; when i truned on all elements and uninstalled the extension, it worked as well again.

Also, it works with production-preset (debug-settings) as you recommended.

Before i put it into production with php 8.0, it would be a better feeling to have this bug solved.

Is it a bigger issue? Already known what it is?

Many thanks for the fast reply!
Thomas

**Comment by subnoodle** [comment] 2022-12-12 14:16
Hi @CybotTM ,as well i modified:
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_WARNING`
in the php.ini-file.
So, finally it works.
But maybe you could consider to get rid of the warning in the code already.

Thank you! I appreciate your extension.

Th.

**Comment by magicsunday** [comment] 2023-08-10 13:31
@subnoodle 

Is this still an issue? I'm not able to reproduce it.

**Comment by Gitsko** [comment] 2023-12-22 16:43
no answer here, I close the issue, should the problem arise again please open the issue again

**Closed by Gitsko** 2023-12-22 16:43 UTC
Labels: bug, php, not reproducible, TYPO3 v11

**Comment by subnoodle** [comment] 2023-12-23 12:18
Dear @Gitsko,

sorry for the delay.
The issue is rather simple:
Since PHP >=8.0 came into play, every now and then different TYPO3-extensions bring out PHP-WARNINGS as EXCEPTIONS (@CybotTM suggested to tell TYPO3 to not bring out WARNINGS as EXCEPTIONS - the only way i know to do this is to turn on production mode. Is there another way?)
Finally, since PHP geht more and more detailed with types of variables and care more about if they are defined or not, it's best practise to avoid PHP WARNINGS by clean coding.
In this case, it's not so obvious why the extension leads to this issue in ContentObjectRenderer in the TYPO3-core (i guess).

Sorry, cannot give a hint here why it's related to this extension, but seemingly it is.

Thank you for investigating.

And Merry Christmas! 🎄

Thomas
