### ISSUE TITLE
rteckeditorimage-title = null

### ISSUE THREAD

**Issue by prdt3e** [netresearch/t3x-rte_ckeditor_image#65] opened 2019-09-02 13:25 UTC
If I add a picture and edit it afterwards (right mousekey -> edit image) 
rteckeditorimage-title and rteckeditorimage-old inputs was NULL.

**Comment by bobberle101** [comment] 2019-10-02 10:26
i can confirm this bug

**Comment by cyMarvin** [comment] 2019-10-09 09:36
Possible workaround would be to override sys_file_metadata table and change default values of title and alternative to '' (empty string) instead of null.

Possible fix would be to check on null or convert value to string in SelectImageController->infoAction when creating the JsonResponse object.

Current:
93            'alt' => $file->getProperty('alternative'),
94            'title' => $file->getProperty('title'),

Fix - option 1:
93            'alt' => (string)$file->getProperty('alternative'),
94            'title' => (string)$file->getProperty('title'),

Fix - option 2:
93            'alt' => $file->getProperty('alternative') ?? '',
94            'title' => $file->getProperty('title') ?? '',

Tested with rte_ckeditor_image 9.0.3 and TYPO3 9.5.8.

**Comment by prdt3e** [comment] 2019-10-09 10:41
Thank you very much. Can you send a PR?

**Comment by cyMarvin** [comment] 2019-10-09 12:21
I just checked the most recent version from GitHub. Version number is still 9.0.3 though it differs from TER version 9.0.3. Seems to be fixed by commit eaa4c908b19a7c80051dcff4d52c8e62d6a9f8f9.

**Comment by CybotTM** [comment] 2019-10-28 07:30
fixed in [9.0.4](https://github.com/netresearch/t3x-rte_ckeditor_image/releases/tag/v9.0.4)

**Closed by CybotTM** 2019-10-28 07:30 UTC
Labels: bug
